spring:
  application:
    name: longkathon

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mallAPI?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Glory019182!

  web:
    cors:
      allowed-origins: http://localhost:3000

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: create
      generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    open-in-view: true
